name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Publish
    runs-on: windows-latest
    steps:
    - name: Checkout code into VM
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.401
    - name: Build with dotnet
      run: cd EagleServer && dotnet build --configuration Release
      shell: cmd
    - name: Pack
      run: cd EagleServer && dotnet pack
      shell: cmd
    - name: Push to Nuget with dotnet
      run: dotnet nuget push .\EagleServer\bin\Debug\EagleServer.*.nupkg -s nuget.org -k %NUGET_KEY% -n true
      shell: cmd
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}